name: Construye el proyecto

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  compila-con-maven:

    runs-on: ubuntu-latest

    steps:
    - name: Descarga el proyecto
      uses: actions/checkout@v3
      
    - name: Configura Java con JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
        
    - name: Compila con Maven
      run: mvn -B package --file pom.xml
